exclude:
  # ライブラリ以外は exclude
  # - Library/Competitive.Library
  # - Library/LibraryChecker
  - Library/LibraryChecker/Program.cs
  - Library/Competitive.Library.Test
  - .github
  - .verify-helper
  - .vscode
  - bin
  - Competitive
  - Competitive.Runner
  - JOI
  - poem
  - tenkei90
  - tools
