[languages.csharp]
csproj_template = ".verify-helper/runner.csproj.xml"
bak_static_embedding = """

// 実行用に埋め込む
partial class Program{Kzrnm.Competitive.ConsoleOutput? Calc() => null;bool __ManyTestCases = false;}
"""