//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kzrnm.Competitive.Analyzer.Diagnostics {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DiagnosticsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiagnosticsResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kzrnm.Competitive.Analyzer.Diagnostics.DiagnosticsResources", typeof(DiagnosticsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Implicit cast 32 bit number to 64 bit number: &apos;{0}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KZCOMPETITIVE0001_KZCOMPETITIVE0002_MessageFormat {
            get {
                return ResourceManager.GetString("KZCOMPETITIVE0001_KZCOMPETITIVE0002_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   32 bit number multiply expression is assigned to 64 bit number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KZCOMPETITIVE0001_Title {
            get {
                return ResourceManager.GetString("KZCOMPETITIVE0001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   32 bit number shift expression is assigned to 64 bit number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KZCOMPETITIVE0002_Title {
            get {
                return ResourceManager.GetString("KZCOMPETITIVE0002_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operator method &apos;{0}&apos; doesn&apos;t have MethodImpl attribute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KZCOMPETITIVE0003_MessageFormat {
            get {
                return ResourceManager.GetString("KZCOMPETITIVE0003_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operator method doesn&apos;t have MethodImpl attribute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KZCOMPETITIVE0003_Title {
            get {
                return ResourceManager.GetString("KZCOMPETITIVE0003_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not defined operator type: &apos;{0}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KZCOMPETITIVE0004_MessageFormat {
            get {
                return ResourceManager.GetString("KZCOMPETITIVE0004_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not defined operator type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KZCOMPETITIVE0004_Title {
            get {
                return ResourceManager.GetString("KZCOMPETITIVE0004_Title", resourceCulture);
            }
        }
    }
}
