//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Competitive.Runner {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InOut {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InOut() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Competitive.Runner.InOut", typeof(InOut).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   9
        ///TE 10 5
        ///BM 0 0
        ///CLE 5 0
        ///HOR 6 5
        ///BN 11 0
        ///CMA 15 5
        ///GA 14 5
        ///BO 12 10
        ///CN 7 10
        ///6
        ///BM
        ///CLE
        ///BN
        ///CMA
        ///BO
        ///CN に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A_IN {
            get {
                return ResourceManager.GetString("A_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HOR
        ///TE
        ///GA に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A_OUT {
            get {
                return ResourceManager.GetString("A_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   12
        ///: 0 20
        ///! 10 20
        ///&quot; 20 20
        ///# 30 20
        ///$ 1 10
        ///% 11 10
        ///&amp; 21 10
        ///&apos; 31 10
        ///( 2 0
        ///) 12 0
        ///* 22 0
        ///+ 32 0
        ///6
        ///$
        ///!
        ///&quot;
        ///&apos;
        ///*
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string B_IN {
            get {
                return ResourceManager.GetString("B_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %
        ///&amp; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string B_OUT {
            get {
                return ResourceManager.GetString("B_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string C_IN {
            get {
                return ResourceManager.GetString("C_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string C_OUT {
            get {
                return ResourceManager.GetString("C_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string D_IN {
            get {
                return ResourceManager.GetString("D_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string D_OUT {
            get {
                return ResourceManager.GetString("D_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E_IN {
            get {
                return ResourceManager.GetString("E_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E_OUT {
            get {
                return ResourceManager.GetString("E_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string F_IN {
            get {
                return ResourceManager.GetString("F_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string F_OUT {
            get {
                return ResourceManager.GetString("F_OUT", resourceCulture);
            }
        }
    }
}
