lang: ja
highlightjs-style: vs
exclude: []
filename-index: true
consolidate:
  - Competitive.Library/BinarySearchTree/
  - Competitive.Library/BinarySearchTree/Internal/
  - Checker/
  - Competitive.Library.Test/