name: test

on:
  push:
    branches:
      - master
    paths:
      - "Library/**"
      - "!**.md"
  pull_request:
    types: [opened, synchronize]
    paths:
      - "Library/**"
      - "!**.md"
  workflow_dispatch:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  NUGET_XMLDOC_MODE: skip
  WORKFLOW_BUILD_SLN: Library/Competitive.Library.sln

jobs:
  test:
    uses: kzrnm/dotnet-actions/.github/workflows/unittest.yml@v1
    with:
      target: Library/Competitive.Library.sln
      os: ubuntu-latest
      dotnet-version: |
        3.1.x
        6.0.x
      test-logger: GitHubActions
