name: test

on:
  push:
    branches:
      - master
    paths:
      - "LibraryChecker/**"
      - "Competitive.Library/**"
      - "Competitive.Library.Test/**"
      - "!**.md"
  pull_request:
    types: [opened, synchronize]
    paths:
      - "LibraryChecker/**"
      - "Competitive.Library/**"
      - "Competitive.Library.Test/**"
      - "!**.md"

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  NUGET_XMLDOC_MODE: skip
  WORKFLOW_BUILD_SLN: Competitive.Library/Competitive.Library.sln

jobs:
  library-checker:
    uses: kzrnm/Competitive.LibraryChecker/.github/workflows/competitive-library-checker.yml@v1
    with:
      target: LibraryChecker/LibraryChecker.csproj
      dll-name: LibraryChecker.dll
      dotnet-version: |
            3.1.x
            6.0.x
      timeout-coefficient: 1.2


  test:
    uses: kzrnm/dotnet-actions/.github/workflows/unittest.yml@v1
    with:
      target: Competitive.Library/Competitive.Library.sln
      os: ubuntu-latest
      dotnet-version: |
        3.1.x
        6.0.x
      test-logger: GitHubActions
