name: test

on:
  push:
    branches:
      - master
    paths:
      - "LibraryChecker/**"
      - "Competitive.Library/**"
      - "Competitive.Library.Test/**"
      - "!**.md"
  pull_request:
    types: [opened, synchronize]
    paths:
      - "LibraryChecker/**"
      - "Competitive.Library/**"
      - "Competitive.Library.Test/**"
      - "!**.md"

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  NUGET_XMLDOC_MODE: skip
  WORKFLOW_BUILD_SLN: Competitive.Library/Competitive.Library.sln

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            3.1.x
            6.0.x
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - run: dotnet tool install -g SourceExpander.Console
      - uses: actions/setup-python@v1
      - run: pip3 install git+https://github.com/kzrnm/verification-helper
      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: oj-verify all

  test:
    uses: kzrnm/dotnet-actions/.github/workflows/unittest.yml@v1
    with:
      target: Competitive.Library/Competitive.Library.sln
      os: ubuntu-latest
      dotnet-version: |
        3.1.x
        6.0.x
      test-logger: GitHubActions
